### ISSUE TITLE
Not using 'flip' throws

### ISSUE THREAD

**Issue by Nicholaiii** [Pictogrammers/svg-icon#3]
Because you are calling toLowerCase on a potentially null value, it throws whenever you don't use flip. 
![image](https://user-images.githubusercontent.com/7280931/132241026-1ef27383-6830-486c-93d8-37bd2df3d686.png)

**Comment by JamesCoyle** [comment]
Good catch. Must have been tired when I coded that... Just published a fix to [NPM](https://www.npmjs.com/package/@jamescoyle/svg-icon/v/0.1.1).
